typography_spectrum: 1
color:
  brandColors:
    - '#181d23'
    - '#314b2a'
    - '#49627f'
    - '#5e8235'
    - '#82a98d'
  brandStrength: 0.7131612475495785
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6775344042107462
analytics:
  google: UA-61994900-1
  facebook: null
  twitter: null
name: D4
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'From Science Fiction to Reality: The Evolution of Artificial Intelligence'
    id: 817daa93-5db5-4bcc-91de-e8b08d1c1ed0
    type: content
  - name: Super Awesome
    url: 'https://projects.invisionapp.com/d/main#/projects/6191786'
    type: external
  - name: Head over heals for AI
    id: cf8bc19e-d023-4246-93ad-84dfdf47ce58
    type: content
  - name: Ex-Googler...
    id: 5ef37f68-f878-4cb1-8626-f255ab2f12fb
    type: content
favicon: 'https://s3-us-west-2.amazonaws.com/cdn.thegrid.io/favlogos/d-favicon.png'
collections:
  - filter:
      notType:
        type: WebPage
    index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
  - filter:
      type:
        type: Article
    permalink:
      path: '/:title/'
  - filter:
      type:
        type: WebPage
    permalink:
      path: '/:title/'
      navigable: true
title: Dan Tocchini
description: Respect the Grid
purpose:
  - id: cfe83a4a-835c-4bbb-a62f-d1a17f064e18
    type: external
    value: 'https://thegrid.io/'
    label: Get on the Grid
  - id: dba2f10d-a5af-42d1-a538-a20a68d82443
    type: external
    value: 'https://github.com/d4tocchini'
    label: Follow my code
